{
 "openapi": "3.1.0",
 "info": {
  "title": "Pivity",
  "description": "Welcome to the Pivity API! You can use our API to access Pivity API endpoints, which can be used interact with any Pivity marketplace programmatically.\n\n# Tenant scoping\nRequests to the Pivity API are not scoped to a specific tenant by default. This means you can see and interact with resources from any Pivity marketplace.\nIn order to only see and interact with the resources for a specific marketplace you can provide an `X-Tenant` header. Valid values for this header are:\n[...]",
  "version": "3.1.0",
  "x-logo": {
   "url": "https://media.gmodstore.com/_/build/img/pivity/logo_padded.png",
   "backgroundColor": "#111111",
   "href": "https://pivity.com"
  }
 },
 "servers": [
  {
   "url": "https://api.pivity.com",
   "description": "The main Pivity API endpoint"
  }
 ],
 "paths": {
  "/v3/me": {
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "Fetch the current authenticated user and their access token",
    "operationId": "getMe"
   }
  },
  "/v3/2fa/nonces/totp/exchange": {
   "post": {
    "summary": "Exchange a TOTP code for a Nonce, which can in-turn be used to call protected endpoints.",
    "operationId": "exchangeTotpForNonce",
    "x-internal": true
   }
  },
  "/v3/me/personal-access-tokens": {
   "get": {
    "tags": [
     "Personal Access Tokens"
    ],
    "summary": "List all the current user's personal access tokens",
    "operationId": "listPersonalAccessTokens",
    "security": [
     {
      "PersonalAccessToken": [
       "personal-access-tokens:read"
      ]
     }
    ],
    "x-internal": true
   },
   "post": {
    "tags": [
     "Personal Access Tokens"
    ],
    "summary": "Create a new personal access token for the current user",
    "operationId": "createPersonalAccessToken",
    "security": [
     {
      "PersonalAccessToken": [
       "personal-access-tokens:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/me/personal-access-tokens/{personal_access_token}": {
   "get": {
    "tags": [
     "Personal Access Tokens"
    ],
    "summary": "Get a personal access token belonging to the current user",
    "operationId": "getPersonalAccessToken",
    "security": [
     {
      "PersonalAccessToken": [
       "personal-access-tokens:read"
      ]
     }
    ],
    "x-internal": true
   },
   "put": {
    "tags": [
     "Personal Access Tokens"
    ],
    "summary": "Update a personal access token",
    "operationId": "updatePersonalAccessToken",
    "security": [
     {
      "PersonalAccessToken": [
       "personal-access-tokens:write"
      ]
     }
    ],
    "x-internal": true
   },
   "delete": {
    "tags": [
     "Personal Access Tokens"
    ],
    "summary": "Delete the specified personal access token",
    "operationId": "deletePersonalAccessToken",
    "security": [
     {
      "PersonalAccessToken": [
       "personal-access-tokens:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/permission-groups/batch": {
   "get": {
    "tags": [
     "Permission Groups"
    ],
    "summary": "Fetch a batch of permission groups by id",
    "operationId": "getPermissionGroups",
    "security": [
     {
      "PersonalAccessToken": [
       "permission-groups:read"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/permission-groups": {
   "get": {
    "tags": [
     "Permission Groups"
    ],
    "summary": "List all permission groups",
    "operationId": "listPermissionGroups",
    "security": [
     {
      "PersonalAccessToken": [
       "permission-groups:read"
      ]
     }
    ],
    "x-internal": true
   },
   "post": {
    "tags": [
     "Permission Groups"
    ],
    "summary": "Create a permission group",
    "operationId": "createPermissionGroup",
    "security": [
     {
      "PersonalAccessToken": [
       "permission-groups:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/permission-groups/{permission_group}": {
   "get": {
    "tags": [
     "Permission Groups"
    ],
    "summary": "Show the specified permission group",
    "operationId": "getPermissionGroup",
    "security": [
     {
      "PersonalAccessToken": [
       "permission-groups:read"
      ]
     }
    ],
    "x-internal": true
   },
   "put": {
    "tags": [
     "Permission Groups"
    ],
    "summary": "Update the specified permission group",
    "operationId": "updatePermissionGroup",
    "security": [
     {
      "PersonalAccessToken": [
       "permission-groups:write"
      ]
     }
    ],
    "x-internal": true
   },
   "delete": {
    "tags": [
     "Permission Groups"
    ],
    "summary": "Delete the specified permission group",
    "operationId": "deletePermissionGroup",
    "security": [
     {
      "PersonalAccessToken": [
       "permission-groups:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/teams/batch": {
   "get": {
    "tags": [
     "Teams"
    ],
    "summary": "Fetch a batch of teams by id",
    "operationId": "getTeams",
    "security": [
     {
      "PersonalAccessToken": [
       "teams:read"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/teams/{team}/webhook-endpoints/test": {
   "post": {
    "tags": [
     "Team Webhook Endpoints"
    ],
    "summary": "Send a test webhook to the endpoints in a team.",
    "operationId": "testTeamWebhookEndpoints",
    "security": [
     {
      "PersonalAccessToken": [
       "team-webhook-endpoints:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/teams/{team}/webhook-endpoints/{webhook_endpoint}/attempts/{webhook_message}/resend": {
   "post": {
    "tags": [
     "Team Webhook Endpoints"
    ],
    "summary": "Resend a webhook attempt for an endpoint",
    "operationId": "resendTeamWebhookEndpointAttempt",
    "security": [
     {
      "PersonalAccessToken": [
       "team-webhook-endpoints:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/teams": {
   "get": {
    "tags": [
     "Teams"
    ],
    "summary": "List all teams",
    "operationId": "listTeams",
    "security": [
     {
      "PersonalAccessToken": [
       "teams:read"
      ]
     }
    ],
    "x-internal": true
   },
   "post": {
    "tags": [
     "Teams"
    ],
    "summary": "Create a new team",
    "operationId": "createTeam",
    "security": [
     {
      "PersonalAccessToken": [
       "teams:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/teams/{team}": {
   "get": {
    "tags": [
     "Teams"
    ],
    "summary": "Fetch the specified team",
    "operationId": "getTeam",
    "security": [
     {
      "PersonalAccessToken": [
       "teams:read"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Teams"
    ],
    "summary": "Update the specified team",
    "operationId": "updateTeam",
    "security": [
     {
      "PersonalAccessToken": [
       "teams:write"
      ]
     }
    ],
    "x-internal": true
   },
   "delete": {
    "tags": [
     "Teams"
    ],
    "summary": "Delete the specified team",
    "operationId": "deleteTeam",
    "security": [
     {
      "PersonalAccessToken": [
       "teams:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/teams/{team}/users": {
   "get": {
    "tags": [
     "Team Users"
    ],
    "summary": "List all users in a team",
    "operationId": "listTeamUsers",
    "security": [
     {
      "PersonalAccessToken": [
       "team-users:read"
      ]
     }
    ]
   }
  },
  "/v3/teams/{team}/webhook-endpoints": {
   "get": {
    "tags": [
     "Team Webhook Endpoints"
    ],
    "summary": "List all webhook endpoints in a team",
    "operationId": "listTeamWebhookEndpoints",
    "security": [
     {
      "PersonalAccessToken": [
       "team-webhook-endpoints:read"
      ]
     }
    ],
    "x-internal": true
   },
   "post": {
    "tags": [
     "Team Webhook Endpoints"
    ],
    "summary": "Create a new webhook endpoint for the given team",
    "operationId": "createTeamWebhookEndpoint",
    "security": [
     {
      "PersonalAccessToken": [
       "team-webhook-endpoints:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/teams/{team}/webhook-endpoints/{webhook_endpoint}": {
   "get": {
    "tags": [
     "Team Webhook Endpoints"
    ],
    "summary": "Fetch a webhook endpoint",
    "operationId": "getTeamWebhookEndpoint",
    "security": [
     {
      "PersonalAccessToken": [
       "team-webhook-endpoints:read"
      ]
     }
    ],
    "x-internal": true
   },
   "put": {
    "tags": [
     "Team Webhook Endpoints"
    ],
    "summary": "Update a webhook endpoint",
    "operationId": "updateTeamWebhookEndpoint",
    "security": [
     {
      "PersonalAccessToken": [
       "team-webhook-endpoints:write"
      ]
     }
    ],
    "x-internal": true
   },
   "delete": {
    "tags": [
     "Team Webhook Endpoints"
    ],
    "summary": "Delete webhook endpoint",
    "operationId": "deleteTeamWebhookEndpoint",
    "security": [
     {
      "PersonalAccessToken": [
       "team-webhook-endpoints:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/teams/{team}/webhook-endpoints/{webhook_endpoint}/secret": {
   "get": {
    "tags": [
     "Team Webhook Endpoints"
    ],
    "summary": "Fetch the secret for the given webhook endpoint.",
    "operationId": "getTeamWebhookEndpointSecret",
    "security": [
     {
      "PersonalAccessToken": [
       "team-webhook-endpoints:read"
      ]
     }
    ],
    "x-internal": true
   },
   "put": {
    "tags": [
     "Team Webhook Endpoints"
    ],
    "summary": "Update the secret for the given webhook endpoint.",
    "operationId": "updateTeamWebhookEndpointSecret",
    "security": [
     {
      "PersonalAccessToken": [
       "team-webhook-endpoints:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/teams/{team}/webhook-endpoints/{webhook_endpoint}/attempts": {
   "get": {
    "tags": [
     "Team Webhook Endpoints"
    ],
    "summary": "List all webhook attempts for an endpoint",
    "operationId": "listTeamWebhookEndpointAttempts",
    "security": [
     {
      "PersonalAccessToken": [
       "team-webhook-endpoints:read"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/teams/{team}/webhook-messages": {
   "get": {
    "tags": [
     "Team Webhook Messages"
    ],
    "summary": "List all webhook messages",
    "operationId": "listTeamWebhookMessages",
    "security": [
     {
      "PersonalAccessToken": [
       "team-webhook-messages:read"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/teams/{team}/webhook-messages/{webhook_message}": {
   "get": {
    "tags": [
     "Team Webhook Messages"
    ],
    "summary": "Fetch a webhook message",
    "operationId": "getTeamWebhookMessage",
    "security": [
     {
      "PersonalAccessToken": [
       "team-webhook-messages:read"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/teams/{team}/webhook-messages/{webhook_message}/attempts": {
   "get": {
    "tags": [
     "Team Webhook Messages"
    ],
    "summary": "List all attempts for a webhook message",
    "operationId": "listTeamWebhookMessageAttempts",
    "security": [
     {
      "PersonalAccessToken": [
       "team-webhook-messages:read"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/products/batch": {
   "get": {
    "tags": [
     "Products"
    ],
    "summary": "Get a batch of products by id",
    "operationId": "getProducts",
    "security": [
     {
      "PersonalAccessToken": [
       "products:read"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/products/{product}/coupons": {
   "get": {
    "tags": [
     "Product Coupons"
    ],
    "summary": "List all coupons for a product",
    "operationId": "listProductCoupons",
    "security": [
     {
      "PersonalAccessToken": [
       "product-coupons:read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Product Coupons"
    ],
    "summary": "Create a coupon for a product",
    "operationId": "createProductCoupon",
    "security": [
     {
      "PersonalAccessToken": [
       "product-coupons:write"
      ]
     }
    ]
   }
  },
  "/v3/products/{product}/coupons/{coupon}": {
   "get": {
    "tags": [
     "Product Coupons"
    ],
    "summary": "Show the specified coupon for a product",
    "operationId": "getProductCoupon",
    "security": [
     {
      "PersonalAccessToken": [
       "product-coupons:read"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Product Coupons"
    ],
    "summary": "Update the specified coupon for a product",
    "operationId": "updateProductCoupon",
    "security": [
     {
      "PersonalAccessToken": [
       "product-coupons:write"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Product Coupons"
    ],
    "summary": "Delete the specified coupon for a product",
    "operationId": "deleteProductCoupon",
    "security": [
     {
      "PersonalAccessToken": [
       "product-coupons:write"
      ]
     }
    ]
   }
  },
  "/v3/products/{product}/purchases": {
   "get": {
    "tags": [
     "Product Purchases"
    ],
    "summary": "List all purchases for a product",
    "operationId": "listProductPurchases",
    "security": [
     {
      "PersonalAccessToken": [
       "product-purchases:read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Product Purchases"
    ],
    "summary": "Create a purchase for a product",
    "operationId": "createProductPurchase",
    "security": [
     {
      "PersonalAccessToken": [
       "product-purchases:write"
      ]
     }
    ]
   }
  },
  "/v3/products/{product}/purchases/{purchase}": {
   "get": {
    "tags": [
     "Product Purchases"
    ],
    "summary": "Show the specified purchase for a product",
    "operationId": "getProductPurchase",
    "security": [
     {
      "PersonalAccessToken": [
       "product-purchases:read"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Product Purchases"
    ],
    "summary": "Update the specified purchase for a product",
    "operationId": "updateProductPurchase",
    "security": [
     {
      "PersonalAccessToken": [
       "product-purchases:write"
      ]
     }
    ]
   }
  },
  "/v3/products/{product}/reviews": {
   "get": {
    "tags": [
     "Product Reviews"
    ],
    "summary": "List all reviews for a product",
    "operationId": "listProductReviews",
    "security": [
     {
      "PersonalAccessToken": [
       "product-reviews:read"
      ]
     }
    ]
   }
  },
  "/v3/products/{product}/reviews/{review}": {
   "get": {
    "tags": [
     "Product Reviews"
    ],
    "summary": "Show the specified review for a product",
    "operationId": "getProductReview",
    "security": [
     {
      "PersonalAccessToken": [
       "product-reviews:read"
      ]
     }
    ]
   }
  },
  "/v3/products/{product}/tickets": {
   "get": {
    "tags": [
     "Product Tickets"
    ],
    "summary": "List all tickets for a product",
    "operationId": "listProductTickets",
    "security": [
     {
      "PersonalAccessToken": [
       "tickets:read"
      ]
     }
    ]
   }
  },
  "/v3/products/{product}/versions": {
   "get": {
    "tags": [
     "Product Versions"
    ],
    "summary": "List all versions for a product",
    "operationId": "listProductVersions",
    "security": [
     {
      "PersonalAccessToken": [
       "product-versions:read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Product Versions"
    ],
    "summary": "Create a version for a product",
    "operationId": "createProductVersion",
    "security": [
     {
      "PersonalAccessToken": [
       "product-versions:write"
      ]
     }
    ]
   }
  },
  "/v3/products/{product}/versions/{version}": {
   "get": {
    "tags": [
     "Product Versions"
    ],
    "summary": "Show the specified version for a product",
    "operationId": "getProductVersion",
    "security": [
     {
      "PersonalAccessToken": [
       "product-versions:read"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Product Versions"
    ],
    "summary": "Update the specified version for a product",
    "operationId": "updateProductVersion",
    "security": [
     {
      "PersonalAccessToken": [
       "product-versions:write"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Product Versions"
    ],
    "summary": "Delete the specified version for a product",
    "operationId": "deleteProductVersion",
    "security": [
     {
      "PersonalAccessToken": [
       "product-versions:write"
      ]
     }
    ]
   }
  },
  "/v3/products/{product}/versions/{version}/download": {
   "post": {
    "tags": [
     "Product Versions"
    ],
    "summary": "Get a one time use url for downloading a product",
    "operationId": "getProductDownloadUrl",
    "security": [
     {
      "PersonalAccessToken": [
       "product-versions:download"
      ]
     }
    ]
   }
  },
  "/v3/products/{product}/media": {
   "get": {
    "tags": [
     "Product Media"
    ],
    "summary": "List all media for a product",
    "operationId": "listProductMedia",
    "security": [
     {
      "PersonalAccessToken": [
       "product-media:read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Product Media"
    ],
    "summary": "Create a medium for a product",
    "description": "If `type` is `image` then the `image` field will be required.\n\nIf `type` is `video` then the `video` field will be required.\n\nIf `type` is `youtube` then the `youtube` field will be required.",
    "operationId": "createProductMedium",
    "security": [
     {
      "PersonalAccessToken": [
       "product-media:write"
      ]
     }
    ]
   }
  },
  "/v3/products/{product}/media/{medium}": {
   "get": {
    "tags": [
     "Product Media"
    ],
    "summary": "Get the specified medium for a product",
    "operationId": "getProductMedium",
    "security": [
     {
      "PersonalAccessToken": [
       "product-media:read"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Product Media"
    ],
    "summary": "Update the specified medium for a product",
    "operationId": "updateProductMedia",
    "security": [
     {
      "PersonalAccessToken": [
       "product-media:write"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Product Media"
    ],
    "summary": "Delete the specified medium for a product",
    "operationId": "deleteProductMedium",
    "security": [
     {
      "PersonalAccessToken": [
       "product-media:write"
      ]
     }
    ]
   }
  },
  "/v3/products/{product}/media/background": {
   "post": {
    "tags": [
     "Product Media"
    ],
    "summary": "Upload/replace the background image for a product.",
    "description": "The image must be 1920 x 670px.",
    "operationId": "uploadProductBackground",
    "security": [
     {
      "PersonalAccessToken": [
       "product-media:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/products/{product}/media/page-header": {
   "post": {
    "tags": [
     "Product Media"
    ],
    "summary": "Upload/replace the page header image for a product.",
    "description": "The image must be 920 x 260px.",
    "operationId": "uploadProductPageHeader",
    "security": [
     {
      "PersonalAccessToken": [
       "product-media:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/products/{product}/media/big-header": {
   "post": {
    "tags": [
     "Product Media"
    ],
    "summary": "Upload/replace the big header image for a product.",
    "description": "The image must be 900 x 415px.",
    "operationId": "uploadProductBigHeader",
    "security": [
     {
      "PersonalAccessToken": [
       "product-media:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/products/{product}/media/listing-header": {
   "post": {
    "tags": [
     "Product Media"
    ],
    "summary": "Upload/replace the listing image for a product.",
    "description": "The image must be 280 x 120px.",
    "operationId": "uploadProductListingHeader",
    "security": [
     {
      "PersonalAccessToken": [
       "product-media:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/teams/{team}/products": {
   "get": {
    "tags": [
     "Products"
    ],
    "summary": "List all products for a team",
    "operationId": "listProducts",
    "security": [
     {
      "PersonalAccessToken": [
       "products:read"
      ]
     }
    ]
   }
  },
  "/v3/products/{product}": {
   "get": {
    "tags": [
     "Products"
    ],
    "summary": "Get the specified product",
    "operationId": "getProduct",
    "security": [
     {
      "PersonalAccessToken": [
       "products:read"
      ]
     }
    ]
   }
  },
  "/v3/users/batch": {
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "Fetch a batch of users by id",
    "operationId": "getUsers",
    "security": [
     {
      "PersonalAccessToken": [
       "users:read"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/users": {
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "List all users",
    "operationId": "listUsers",
    "security": [
     {
      "PersonalAccessToken": [
       "users:read"
      ]
     }
    ]
   }
  },
  "/v3/users/{user}": {
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "Fetch the specified user",
    "operationId": "getUser",
    "security": [
     {
      "PersonalAccessToken": [
       "users:read"
      ]
     }
    ]
   }
  },
  "/v3/users/{user}/teams": {
   "get": {
    "tags": [
     "User Teams"
    ],
    "summary": "List all the specified user's teams",
    "operationId": "listUserTeams",
    "security": [
     {
      "PersonalAccessToken": [
       "teams:read"
      ]
     }
    ]
   }
  },
  "/v3/users/{user}/products": {
   "get": {
    "tags": [
     "User Products"
    ],
    "summary": "List all the specified user's products",
    "operationId": "listUserProducts",
    "security": [
     {
      "PersonalAccessToken": [
       "products:read"
      ]
     }
    ]
   }
  },
  "/v3/users/{user}/badges": {
   "get": {
    "tags": [
     "User Badges"
    ],
    "summary": "List all the specified user's badges",
    "operationId": "listUserBadges",
    "security": [
     {
      "PersonalAccessToken": [
       "user-badges:read"
      ]
     }
    ],
    "x-internal": true
   },
   "post": {
    "tags": [
     "User Badges"
    ],
    "summary": "Attach a badge to a user",
    "operationId": "createUserBadge",
    "security": [
     {
      "PersonalAccessToken": [
       "user-badges:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/users/{user}/badges/{badge}": {
   "delete": {
    "tags": [
     "User Badges"
    ],
    "summary": "Detach a badge from a user",
    "operationId": "deleteUserBadge",
    "security": [
     {
      "PersonalAccessToken": [
       "user-badges:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/users/{user}/bans": {
   "get": {
    "tags": [
     "User Bans"
    ],
    "summary": "List all the specified user's bans",
    "operationId": "listUserBans",
    "security": [
     {
      "PersonalAccessToken": [
       "user-bans:read"
      ]
     }
    ]
   }
  },
  "/v3/users/{user}/purchases": {
   "get": {
    "tags": [
     "User Product Purchases"
    ],
    "summary": "List all the specified user's purchases",
    "operationId": "listUserPurchases",
    "security": [
     {
      "PersonalAccessToken": [
       "user-purchases:read"
      ]
     }
    ]
   }
  },
  "/v3/tickets/{ticket}": {
   "get": {
    "tags": [
     "Tickets"
    ],
    "summary": "Fetch the specified ticket",
    "operationId": "getTicket",
    "security": [
     {
      "PersonalAccessToken": [
       "tickets:read"
      ]
     }
    ],
    "x-internal": true
   },
   "put": {
    "tags": [
     "Tickets"
    ],
    "summary": "Update the specified ticket",
    "operationId": "updateTicket",
    "security": [
     {
      "PersonalAccessToken": [
       "tickets:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/tickets/batch": {
   "get": {
    "tags": [
     "Tickets"
    ],
    "summary": "Fetch a batch of tickets by id",
    "operationId": "getTickets",
    "security": [
     {
      "PersonalAccessToken": [
       "tickets:read"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/tickets/{ticket}/messages": {
   "get": {
    "tags": [
     "Ticket Messages"
    ],
    "summary": "List all messages for a ticket",
    "operationId": "listTicketMessages",
    "security": [
     {
      "PersonalAccessToken": [
       "ticket-messages:read"
      ]
     }
    ],
    "x-internal": true
   },
   "post": {
    "tags": [
     "Ticket Messages"
    ],
    "summary": "Create a message for a ticket",
    "operationId": "createTicketMessage",
    "security": [
     {
      "PersonalAccessToken": [
       "ticket-messages:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/tickets/{ticket}/messages/{message}": {
   "get": {
    "tags": [
     "Ticket Messages"
    ],
    "summary": "Fetch the specified ticket message",
    "operationId": "getTicketMessage",
    "security": [
     {
      "PersonalAccessToken": [
       "ticket-messages:read"
      ]
     }
    ],
    "x-internal": true
   },
   "put": {
    "tags": [
     "Ticket Messages"
    ],
    "summary": "Update the specified message for a ticket",
    "operationId": "updateTicketMessage",
    "security": [
     {
      "PersonalAccessToken": [
       "ticket-messages:write"
      ]
     }
    ],
    "x-internal": true
   },
   "delete": {
    "tags": [
     "Ticket Messages"
    ],
    "summary": "Delete the specified message for a ticket",
    "operationId": "deleteTicketMessage",
    "security": [
     {
      "PersonalAccessToken": [
       "ticket-messages:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/tickets/{ticket}/messages/{message}/restore": {
   "patch": {
    "tags": [
     "Ticket Messages"
    ],
    "summary": "Restore the specified message for a ticket",
    "operationId": "restoreTicketMessage",
    "security": [
     {
      "PersonalAccessToken": [
       "ticket-messages:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/tickets/{ticket}/messages/{message}/revisions": {
   "get": {
    "tags": [
     "Ticket Messages"
    ],
    "summary": "List all revisions for a ticket message",
    "operationId": "listTicketMessageRevisions",
    "security": [
     {
      "PersonalAccessToken": [
       "ticket-messages:read"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/tickets/{ticket}/messages/{message}/revisions/{revision}": {
   "get": {
    "tags": [
     "Ticket Messages"
    ],
    "summary": "Fetch the specified ticket message revision",
    "operationId": "getTicketMessageRevision",
    "security": [
     {
      "PersonalAccessToken": [
       "ticket-messages:read"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/tickets/{ticket}/attachments": {
   "get": {
    "tags": [
     "Ticket Attachments"
    ],
    "summary": "List all attachments for a ticket",
    "operationId": "listTicketAttachments",
    "security": [
     {
      "PersonalAccessToken": [
       "ticket-attachments:read"
      ]
     }
    ],
    "x-internal": true
   },
   "post": {
    "tags": [
     "Ticket Attachments"
    ],
    "summary": "Create an attachment for a ticket",
    "operationId": "createTicketAttachment",
    "security": [
     {
      "PersonalAccessToken": [
       "ticket-attachments:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/tickets/{ticket}/attachments/{attachment}": {
   "get": {
    "tags": [
     "Ticket Attachments"
    ],
    "summary": "Fetch the specified ticket attachment",
    "operationId": "getTicketAttachment",
    "security": [
     {
      "PersonalAccessToken": [
       "ticket-attachments:read"
      ]
     }
    ],
    "x-internal": true
   },
   "delete": {
    "tags": [
     "Ticket Attachments"
    ],
    "summary": "Delete the specified attachment for a ticket",
    "operationId": "deleteTicketAttachment",
    "security": [
     {
      "PersonalAccessToken": [
       "ticket-attachments:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/tickets/log-requests/{logRequestId}": {
   "post": {
    "tags": [
     "Ticket Log Requests"
    ],
    "summary": "List all messages for a ticket",
    "operationId": "uploadLogToTicket",
    "x-internal": true
   }
  },
  "/v3/tickets/{ticket}/tags": {
   "get": {
    "tags": [
     "Ticket Tags"
    ],
    "summary": "List all tags for a ticket",
    "operationId": "listTicketTags",
    "security": [
     {
      "PersonalAccessToken": [
       "ticket-tags:read"
      ]
     }
    ],
    "x-internal": true
   },
   "post": {
    "tags": [
     "Ticket Tags"
    ],
    "summary": "Add a tag to a ticket",
    "operationId": "createTicketTag",
    "security": [
     {
      "PersonalAccessToken": [
       "ticket-tags:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/tickets/{ticket}/tags/{tag}": {
   "delete": {
    "tags": [
     "Ticket Tags"
    ],
    "summary": "Delete the specified tag on a ticket",
    "operationId": "deleteTicketTag",
    "security": [
     {
      "PersonalAccessToken": [
       "ticket-tags:write"
      ]
     }
    ],
    "x-internal": true
   }
  },
  "/v3/media/upload": []
 },
 "webhooks": {
  "ProductPurchaseCreated": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "ProductPurchaseCreated",
    "description": "A product purchase has been created",
    "security": []
   }
  },
  "ProductPurchaseDeleted": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "ProductPurchaseDeleted",
    "description": "A product purchase has been deleted",
    "security": []
   }
  },
  "ProductPurchaseRevoked": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "ProductPurchaseRevoked",
    "description": "A product purchase has been revoked",
    "security": []
   }
  },
  "ProductPurchaseUnrevoked": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "ProductPurchaseUnrevoked",
    "description": "A product purchase has been unrevoked",
    "security": []
   }
  },
  "ProductReviewCreated": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "ProductReviewCreated",
    "description": "A product review has been created",
    "security": []
   }
  },
  "ProductReviewDeleted": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "ProductReviewDeleted",
    "description": "A product review has been deleted",
    "security": []
   }
  },
  "ProductReviewUpdated": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "ProductReviewUpdated",
    "description": "A product review has been updated",
    "security": []
   }
  },
  "ProductVersionCreated": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "ProductVersionCreated",
    "description": "A product version has been created",
    "security": []
   }
  },
  "ProductVersionDeleted": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "ProductVersionDeleted",
    "description": "A product version has been deleted",
    "security": []
   }
  },
  "ProductVersionUpdated": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "ProductVersionUpdated",
    "description": "A product version has been updated",
    "security": []
   }
  },
  "TicketAttachmentCreated": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "TicketAttachmentCreated",
    "description": "An attachment has been uploaded to a ticket",
    "security": []
   }
  },
  "TicketAttachmentDeleted": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "TicketAttachmentDeleted",
    "description": "A ticket attachment has been deleted",
    "security": []
   }
  },
  "TicketMessageCreated": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "TicketMessageCreated",
    "description": "A ticket has been replied to",
    "security": []
   }
  },
  "TicketMessageDeleted": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "TicketMessageDeleted",
    "description": "A ticket reply has been deleted",
    "security": []
   }
  },
  "TicketMessageRestored": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "TicketMessageRestored",
    "description": "A ticket reply has been restored",
    "security": []
   }
  },
  "TicketMessageUpdated": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "TicketMessageUpdated",
    "description": "A ticket reply has been updated",
    "security": []
   }
  },
  "TicketCreated": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "TicketCreated",
    "description": "A ticket has been created for one of your products",
    "security": []
   }
  },
  "TicketHeld": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "TicketHeld",
    "description": "A ticket for one of your products has been put on hold",
    "security": []
   }
  },
  "TicketHidden": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "TicketHidden",
    "description": "A ticket for one of your products has been hidden",
    "security": []
   }
  },
  "TicketLocked": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "TicketLocked",
    "description": "A ticket for one of your products has been locked",
    "security": []
   }
  },
  "TicketTagged": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "TicketTagged",
    "description": "A tag has been added to a ticket",
    "security": []
   }
  },
  "TicketUnheld": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "TicketUnheld",
    "description": "A ticket for one of your products has been taken off hold",
    "security": []
   }
  },
  "TicketUnhidden": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "TicketUnhidden",
    "description": "A ticket for one of your products has been unhidden",
    "security": []
   }
  },
  "TicketUnlocked": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "TicketUnlocked",
    "description": "A ticket for one of your products has been unlocked",
    "security": []
   }
  },
  "TicketUntagged": {
   "post": {
    "tags": [
     "Webhooks"
    ],
    "summary": "TicketUntagged",
    "description": "A tag has been removed from a ticket",
    "security": []
   }
  }
 },
 "components": {
  "securitySchemes": {
   "PersonalAccessToken": {
    "type": "http",
    "scheme": "bearer"
   }
  }
 },
 "security": [
  {
   "PersonalAccessToken": []
  }
 ],
 "tags": [
  {
   "name": "Personal Access Tokens"
  },
  {
   "name": "Products"
  },
  {
   "name": "Product Coupons"
  },
  {
   "name": "Product Purchases"
  },
  {
   "name": "Product Reviews"
  },
  {
   "name": "Product Tickets"
  },
  {
   "name": "Product Versions"
  },
  {
   "name": "Product Media"
  },
  {
   "name": "Permission Groups"
  },
  {
   "name": "Teams"
  },
  {
   "name": "Team Users"
  },
  {
   "name": "Team Webhook Endpoints"
  },
  {
   "name": "Team Webhook Messages"
  },
  {
   "name": "Users"
  },
  {
   "name": "User Badges"
  },
  {
   "name": "User Bans"
  },
  {
   "name": "User Product Purchases"
  },
  {
   "name": "User Products"
  },
  {
   "name": "User Teams"
  },
  {
   "name": "Tickets"
  },
  {
   "name": "Ticket Messages"
  },
  {
   "name": "Ticket Attachments"
  },
  {
   "name": "Ticket Tags"
  },
  {
   "name": "Ticket Log Requests"
  },
  {
   "name": "Webhooks"
  },
  {
   "name": "Media"
  }
 ],
 "x-tagGroups": [
  {
   "name": "Permission Groups",
   "tags": [
    "Permission Groups"
   ]
  },
  {
   "name": "Personal Access Tokens",
   "tags": [
    "Personal Access Tokens"
   ]
  },
  {
   "name": "Products",
   "tags": [
    "Products",
    "Product Coupons",
    "Product Purchases",
    "Product Reviews",
    "Product Versions",
    "Product Tickets",
    "Product Media"
   ]
  },
  {
   "name": "Teams",
   "tags": [
    "Teams",
    "Team Users",
    "Team Webhook Endpoints",
    "Team Webhook Messages"
   ]
  },
  {
   "name": "Users",
   "tags": [
    "Users",
    "User Product Purchases",
    "User Products",
    "User Badges",
    "User Bans",
    "User Teams"
   ]
  },
  {
   "name": "Tickets",
   "tags": [
    "Tickets",
    "Ticket Messages",
    "Ticket Attachments",
    "Ticket Tags"
   ]
  },
  {
   "name": "Webhooks",
   "tags": [
    "Webhooks"
   ]
  }
 ]
}